services:
  app:
    build: .
    container_name: customer_app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama-setup
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  ollama-setup:
    image: curlimages/curl:latest
    container_name: ollama_setup
    depends_on:
      - ollama
    command: >
      sh -c "
      sleep 10 &&
      echo 'Pulling llama3.1:latest model...' &&
      curl -s -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3.1:latest\"}' > /dev/null 2>&1 &&
      echo 'Model Ready!'
      "
    restart: no

volumes:
  ollama:
